ALTER TABLE categories ALTER COLUMN name TYPE citext;
ALTER TABLE customers ALTER COLUMN name TYPE citext;
ALTER TABLE products ALTER COLUMN name TYPE citext;

CREATE POLICY "Enable access to all users" ON storage.objects FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON storage.objects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable insert for authenticated users only" ON storage.buckets FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- public.categories definition

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	name extensions.citext NULL,
	inactive bool NULL DEFAULT false,
	CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.categories OWNER TO supabase_admin;


-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	name extensions.citext NULL,
	phone_1 varchar NULL,
	phone_2 varchar NULL,
	document_type varchar NULL,
	document_number varchar NULL,
	email varchar NULL,
	"notes" text NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.customers OWNER TO supabase_admin;


-- public.measure_units definition

-- Drop table

-- DROP TABLE public.measure_units;

CREATE TABLE public.measure_units (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	name extensions.citext NULL,
	abbreviation varchar NULL,
	inactive bool NULL DEFAULT false,
	CONSTRAINT measure_units_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.measure_units OWNER TO supabase_admin;


-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	name extensions.citext NULL,
	category_id int8 NULL,
	price_to_buy numeric NULL,
	price_to_sell numeric NULL,
	stock_is_automatic bool NULL DEFAULT false,
	stock_amount numeric NULL,
	stock_minimum_amount numeric NULL,
	measure_unit_id int8 NULL,
	code_bar varchar NULL,
	code_internal varchar NULL,
	description text NULL,
	image_name varchar NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.products OWNER TO supabase_admin;


-- public.stock_movement definition

-- Drop table

-- DROP TABLE public.stock_movement;

CREATE TABLE public.stock_movement (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	product_id int8 NULL,
	quantity numeric NULL,
	stock_movement_type varchar NULL,
	CONSTRAINT stock_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.stock_movement OWNER TO supabase_admin;


-- public.store definition

-- Drop table

-- DROP TABLE public.store;

CREATE TABLE public.store (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	name varchar NULL,
	whatsapp varchar NULL,
	color_primary varchar NULL,
	color_secundary varchar NULL,
	url_paralax_image varchar NULL,
	CONSTRAINT store_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.store OWNER TO supabase_admin;


-- public.categories foreign keys

ALTER TABLE public.categories ADD CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


-- public.customers foreign keys

ALTER TABLE public.customers ADD CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


-- public.measure_units foreign keys

ALTER TABLE public.measure_units ADD CONSTRAINT measure_units_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


-- public.products foreign keys

ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE public.products ADD CONSTRAINT products_measure_unit_id_fkey FOREIGN KEY (measure_unit_id) REFERENCES public.measure_units(id);
ALTER TABLE public.products ADD CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


-- public.stock_movement foreign keys

ALTER TABLE public.stock_movement ADD CONSTRAINT stock_movement_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


-- public.store foreign keys

ALTER TABLE public.store ADD CONSTRAINT store_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
