-- public.categories definition

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" extensions."citext" NULL,
	active bool NULL DEFAULT true,
	CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.categories OWNER TO supabase_admin;
GRANT ALL ON TABLE public.categories TO postgres;
GRANT ALL ON TABLE public.categories TO supabase_admin;
GRANT ALL ON TABLE public.categories TO anon;
GRANT ALL ON TABLE public.categories TO authenticated;
GRANT ALL ON TABLE public.categories TO service_role;


-- public.categories foreign keys

ALTER TABLE public.categories ADD CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
