-- public.customers definition
-- Drop table
-- DROP TABLE public.customers;
CREATE TABLE public.customers (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  "name" extensions."citext" NULL,
  phone_1 varchar NULL,
  phone_2 varchar NULL,
  document_type varchar NULL,
  document_number varchar NULL,
  email varchar NULL,
  notes text NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
-- public.customers foreign keys
ALTER TABLE public.customers
  ADD CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
