-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" extensions."citext" NULL,
	phone_1 varchar NULL,
	document_number varchar NULL,
	email varchar NULL,
	notes text NULL,
	active bool NULL DEFAULT true,
	phone_2 varchar NULL,
	phone_1_has_whatsapp bool NULL,
	is_legal_entity bool NULL DEFAULT false,
	CONSTRAINT customers_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.customers OWNER TO supabase_admin;
GRANT ALL ON TABLE public.customers TO postgres;
GRANT ALL ON TABLE public.customers TO supabase_admin;
GRANT ALL ON TABLE public.customers TO anon;
GRANT ALL ON TABLE public.customers TO authenticated;
GRANT ALL ON TABLE public.customers TO service_role;


-- public.customers foreign keys

ALTER TABLE public.customers ADD CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
