-- public.orders_products definition

-- Drop table

-- DROP TABLE public.orders_products;

CREATE TABLE public.orders_products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	user_id uuid NULL,
	order_id int8 NULL,
	product_id int8 NULL,
	product_name extensions."citext" NULL,
	unit_price numeric NULL,
	amount numeric NULL,
	CONSTRAINT orders_items_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.orders_products OWNER TO supabase_admin;
GRANT ALL ON TABLE public.orders_products TO postgres;
GRANT ALL ON TABLE public.orders_products TO supabase_admin;
GRANT ALL ON TABLE public.orders_products TO anon;
GRANT ALL ON TABLE public.orders_products TO authenticated;
GRANT ALL ON TABLE public.orders_products TO service_role;


-- public.orders_products foreign keys

ALTER TABLE public.orders_products ADD CONSTRAINT orders_products_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.orders_products ADD CONSTRAINT orders_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.orders_products ADD CONSTRAINT orders_products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
