-- public.products_movement definition

-- Drop table

-- DROP TABLE public.products_movement;

CREATE TABLE public.products_movement (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	product_id int8 NULL,
	amount int4 NULL DEFAULT 0,
	"type" varchar NULL,
	CONSTRAINT stock_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.products_movement OWNER TO supabase_admin;
GRANT ALL ON TABLE public.products_movement TO postgres;
GRANT ALL ON TABLE public.products_movement TO supabase_admin;
GRANT ALL ON TABLE public.products_movement TO anon;
GRANT ALL ON TABLE public.products_movement TO authenticated;
GRANT ALL ON TABLE public.products_movement TO service_role;


-- public.products_movement foreign keys

ALTER TABLE public.products_movement ADD CONSTRAINT products_movement_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.products_movement ADD CONSTRAINT products_movement_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
