-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" extensions."citext" NULL,
	category_id int8 NULL,
	price_to_buy numeric NULL,
	price_to_sell numeric NULL,
        price_profit int8 NULL,
        price_markup int8 NULL,
	has_stock_control bool NULL DEFAULT false,
	stock_amount numeric NULL,
	stock_minimum_amount numeric NULL,
	measure_unit varchar NULL,
	code_bar varchar NULL,
	code_internal varchar NULL,
	description text NULL,
	image_name varchar NULL,
        active bool NULL DEFAULT true,
	CONSTRAINT products_pkey PRIMARY KEY (id)
);


-- public.products foreign keys

ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE public.products ADD CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
