-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" extensions."citext" NULL,
	price numeric NULL DEFAULT '0'::numeric,
	cost_price numeric NULL DEFAULT '0'::numeric,
	measure_unit varchar NULL,
	code_bar varchar NULL,
	details text NULL,
	image_name varchar NULL,
	brand varchar NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.products OWNER TO supabase_admin;
GRANT ALL ON TABLE public.products TO postgres;
GRANT ALL ON TABLE public.products TO supabase_admin;
GRANT ALL ON TABLE public.products TO anon;
GRANT ALL ON TABLE public.products TO authenticated;
GRANT ALL ON TABLE public.products TO service_role;


-- public.products foreign keys

ALTER TABLE public.products ADD CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
