-- public.stock_movement definition

-- Drop table

-- DROP TABLE public.stock_movement;

CREATE TABLE public.stock_movement (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	product_id int8 NULL,
	amount numeric NULL,
	type varchar NULL,
	CONSTRAINT stock_pkey PRIMARY KEY (id)
);


-- public.stock_movement foreign keys

ALTER TABLE public.stock_movement ADD CONSTRAINT stock_movement_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
