-- public.store definition

-- Drop table

-- DROP TABLE public.store;

CREATE TABLE public.store (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id uuid NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" varchar NULL,
	whatsapp varchar NULL,
	color_primary varchar NULL,
	color_secundary varchar NULL,
	url_paralax_image varchar NULL,
	CONSTRAINT store_pkey PRIMARY KEY (id)
);


-- public.store foreign keys

ALTER TABLE public.store ADD CONSTRAINT store_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
